label: styles
abby-moffitt/GA-Semantic pull request #10
Opened 2023-06-01 21:52 UTC by Dart-EY

https://dev.azure.com/EY-GA/Global%20Atlantic%20DevOps/_boards/board/t/Global%20Atlantic%20Component%20Library%20Team/Stories/?workitem=23513

# Description

Styles for the Semantic UI `Label` component.

# Screenshots

![image](https://github.com/abby-moffitt/GA-Semantic/assets/101662434/4ce8c3c2-9f31-4307-91b7-d59ce1107c07)

# Notes

Few things I wanted to highlight:

1. The styles that come from Semantic UI, already have the `!important` tag in them: 

      ![image](https://github.com/abby-moffitt/GA-Semantic/assets/101662434/1343af2b-409c-461d-abcf-6523c3e78b27)

      Hence, I needed to make use of them in order to have our styles reflected.

2. Semantic UI has some styles for the `Label` when it is an `a` tag and it's hovered. I could not find styles in the documentation when it comes to the `outlined` variant. So I followed what we had implemented in the first version of the library. 

3. I did not style the `icon` that's used inside of the `tag`. My thought was that the portal is not using the `Icon` component from Semantic UI, since Semantic doesn't have all the icons that have been used. So the styling of the `icon` should be done separately. 

Please let me know if any of these assumptions were not accurate and if anything needs to be changed!

2023-06-02 18:49 UTC, michael-lynch requested changes
We'll need to keep `!important` on our selectors but it occurred to me that this probably wouldn't be necessary if we were using a Semantic theme, as we would have set the color variables to whatever values we need.

2023-06-02 18:49 UTC, michael-lynch commented on src/styles/label.css
> +.ui.label {
Let's add our `transition: var(--transition-hover)`.

2023-06-02 18:49 UTC, michael-lynch commented on src/components/pages/Theme/Theme.jsx
> +          <div className='row'>
Let's first have a `.row`. of examples that are not interactive and do not have an icon. 

Then we can use the `<Header>` and `.section` class for "Outlined" and "Interactive" sections, like we do the "Disabled" and "Form" checkboxes.

2023-06-02 18:49 UTC, michael-lynch commented on src/components/pages/Theme/Theme.jsx
> +            Chip
I know the design system refers to this as a "Chip", but let's use Semantic terminology and call this "Label." Be sure to reorder it alphabetically.

We can rename the existing "Label" section "Form."

2023-06-02 18:49 UTC, michael-lynch commented on src/components/pages/Theme/Theme.jsx
> +            <Label as='a' color='blue'>
I think the interactive labels should use `as="button"`. We'll just need to add a new selector with `button`.

```
a.ui.label.green:hover,
button.ui.label.green:hover {...}
```

Let's also ensure the `a` and `button` use `cursor: pointer`.

```
a.ui.label,
button.ui.label {
  cursor: pointer;
}
```

2023-06-05 18:52 UTC, michael-lynch commented
Looks good @Dart-EY. Last change - let's just update the `<table>` in the README with a new row for the "Label" component. You may need to merge `develop` back into your branch to see the README.

2023-06-05 18:56 UTC, alva-fresh commented on src/components/pages/Theme/Theme.jsx
> +            Form
maybe _Form Label_ here?

2023-06-05 19:11 UTC, Dart-EY commented on src/components/pages/Theme/Theme.jsx
> +            Form
I believe it's better! Gives more context!

2023-06-05 19:15 UTC, michael-lynch approved these changes

2023-06-05 19:22 UTC, merged